#!/bin/bash

TMP_PATH=/tmp/zui

# Set gonme-terminal nord theme
sudo apt install gnome-terminal -y
git clone --quiet https://github.com/arcticicestudio/nord-gnome-terminal.git ${TMP_PATH}/nord-gnome-terminal
cd ${TMP_PATH}/nord-gnome-terminal/src
bash nord.sh
